# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Display_Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 844)
        MainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1280, 720))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameBackMenu = QtWidgets.QFrame(self.centralwidget)
        self.frameBackMenu.setMinimumSize(QtCore.QSize(0, 0))
        self.frameBackMenu.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frameBackMenu.setStyleSheet("background-color: rgb(213, 222, 64);")
        self.frameBackMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBackMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBackMenu.setObjectName("frameBackMenu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameBackMenu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frameBackMenu)
        self.frame.setMinimumSize(QtCore.QSize(172, 80))
        self.frame.setMaximumSize(QtCore.QSize(172, 100))
        self.frame.setStyleSheet("background-image: url(:/pesquisar/1x/iconLogo.png);\n"
"background-position:center;\n"
"background-repeat: no-repeat;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_menu = QtWidgets.QFrame(self.frameBackMenu)
        self.frame_menu.setMinimumSize(QtCore.QSize(1000, 80))
        self.frame_menu.setMaximumSize(QtCore.QSize(60000, 100))
        self.frame_menu.setToolTipDuration(-1)
        self.frame_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_usuario = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_usuario.setMinimumSize(QtCore.QSize(151, 80))
        self.pushButton_usuario.setMaximumSize(QtCore.QSize(151, 99))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(12)
        self.pushButton_usuario.setFont(font)
        self.pushButton_usuario.setStyleSheet("QPushButton {\n"
"    background-color: rgb(224, 233, 73);\n"
"    color: rgb(0, 53, 62);\n"
"    border:1px solid rgb(94, 104, 28);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 238, 68);\n"
"    border:1px solid rgb(0, 53, 62);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(94, 104, 28);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_usuario.setObjectName("pushButton_usuario")
        self.horizontalLayout_2.addWidget(self.pushButton_usuario)
        self.pushButton_perfil = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_perfil.setMinimumSize(QtCore.QSize(151, 80))
        self.pushButton_perfil.setMaximumSize(QtCore.QSize(151, 99))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(12)
        self.pushButton_perfil.setFont(font)
        self.pushButton_perfil.setStyleSheet("QPushButton {\n"
"    background-color: rgb(224, 233, 73);\n"
"    color: rgb(0, 53, 62);\n"
"    border:1px solid rgb(94, 104, 28);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 238, 68);\n"
"    border:1px solid rgb(0, 53, 62);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(94, 104, 28);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_perfil.setObjectName("pushButton_perfil")
        self.horizontalLayout_2.addWidget(self.pushButton_perfil)
        self.pushButton_sair = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_sair.setMinimumSize(QtCore.QSize(151, 80))
        self.pushButton_sair.setMaximumSize(QtCore.QSize(151, 99))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(12)
        self.pushButton_sair.setFont(font)
        self.pushButton_sair.setStyleSheet("QPushButton {\n"
"    background-color: rgb(224, 233, 73);\n"
"    color: rgb(0, 53, 62);\n"
"    border:1px solid rgb(94, 104, 28);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 238, 68);\n"
"    border:1px solid rgb(0, 53, 62);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(94, 104, 28);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_sair.setObjectName("pushButton_sair")
        self.horizontalLayout_2.addWidget(self.pushButton_sair)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEdit_pesquisar = QtWidgets.QLineEdit(self.frame_menu)
        self.lineEdit_pesquisar.setMinimumSize(QtCore.QSize(380, 63))
        self.lineEdit_pesquisar.setMaximumSize(QtCore.QSize(490, 63))
        font = QtGui.QFont()
        font.setFamily("Asap")
        font.setPointSize(18)
        self.lineEdit_pesquisar.setFont(font)
        self.lineEdit_pesquisar.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: none;\n"
"    padding: 10px;\n"
"    coloc:rgb(77, 77, 77)\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(243, 243, 243);\n"
"}")
        self.lineEdit_pesquisar.setText("")
        self.lineEdit_pesquisar.setMaxLength(32)
        self.lineEdit_pesquisar.setObjectName("lineEdit_pesquisar")
        self.horizontalLayout_2.addWidget(self.lineEdit_pesquisar)
        self.pushButton_pesquisar = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_pesquisar.setMinimumSize(QtCore.QSize(70, 63))
        self.pushButton_pesquisar.setMaximumSize(QtCore.QSize(70, 63))
        self.pushButton_pesquisar.setStyleSheet("QPushButton {\n"
"    background-image: url(:/pesquisar/1x/Prancheta 136.png);\n"
"    background-position:center;\n"
"    background-repeat: no-repeat;\n"
"    background-color: rgb(238, 238, 238);\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/pesquisar/1x/pesquisarhover.png);\n"
"    background-color: rgb(243, 243, 243);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(226, 226, 226);\n"
"}")
        self.pushButton_pesquisar.setText("")
        self.pushButton_pesquisar.setObjectName("pushButton_pesquisar")
        self.horizontalLayout_2.addWidget(self.pushButton_pesquisar)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.frame_Usuario = QtWidgets.QFrame(self.frameBackMenu)
        self.frame_Usuario.setMinimumSize(QtCore.QSize(172, 80))
        self.frame_Usuario.setMaximumSize(QtCore.QSize(172, 100))
        self.frame_Usuario.setStyleSheet("")
        self.frame_Usuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Usuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Usuario.setObjectName("frame_Usuario")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Usuario)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_Foto = QtWidgets.QFrame(self.frame_Usuario)
        self.frame_Foto.setMinimumSize(QtCore.QSize(70, 70))
        self.frame_Foto.setMaximumSize(QtCore.QSize(85, 85))
        self.frame_Foto.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid rgb(94, 104, 28);\n"
"border-radius: 42px;\n"
"box-shadow: 10px")
        self.frame_Foto.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Foto.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Foto.setObjectName("frame_Foto")
        self.gridLayout.addWidget(self.frame_Foto, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_Usuario)
        self.verticalLayout.addWidget(self.frameBackMenu)
        self.frameBody = QtWidgets.QFrame(self.centralwidget)
        self.frameBody.setStyleSheet("background-color: rgb(199, 211, 0);")
        self.frameBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody.setObjectName("frameBody")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameBody)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frameBody)
        self.frame_6.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2.addWidget(self.frame_6, 0, 7, 3, 1)
        self.label = QtWidgets.QLabel(self.frameBody)
        font = QtGui.QFont()
        font.setFamily("Asap Medium")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 53, 62);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frameBody)
        font = QtGui.QFont()
        font.setFamily("Asap Medium")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 53, 62);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frameBody)
        font = QtGui.QFont()
        font.setFamily("Asap Medium")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 53, 62);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 6, 1, 1)
        self.pushButton_RH = QtWidgets.QPushButton(self.frameBody)
        self.pushButton_RH.setMinimumSize(QtCore.QSize(340, 340))
        self.pushButton_RH.setMaximumSize(QtCore.QSize(500, 500))
        self.pushButton_RH.setStyleSheet("QPushButton {\n"
"    background-image: url(:/pesquisar/1x/B_RHhover.png);\n"
"    background-position:center;\n"
"    background-repeat: no-repeat;\n"
"    background-color: rgb(252, 252, 242);\n"
"    border-radius: 15px;\n"
"    box-shadow: 10px 5px 5px black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/pesquisar/1x/B_RH.png);\n"
"    background-color: rgb(0, 53, 62);\n"
"    border:1px solid rgb(0, 53, 62);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 38, 44);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_RH.setText("")
        self.pushButton_RH.setObjectName("pushButton_RH")
        self.gridLayout_2.addWidget(self.pushButton_RH, 1, 5, 1, 1)
        self.pushButton_Compras = QtWidgets.QPushButton(self.frameBody)
        self.pushButton_Compras.setMinimumSize(QtCore.QSize(340, 340))
        self.pushButton_Compras.setMaximumSize(QtCore.QSize(500, 500))
        self.pushButton_Compras.setStyleSheet("QPushButton {\n"
"    background-image: url(:/pesquisar/1x/B_comprashover.png);\n"
"    background-position:center;\n"
"    background-repeat: no-repeat;\n"
"    background-color: rgb(252, 252, 242);\n"
"    border-radius: 15px;\n"
"    box-shadow: 10px 5px 5px black;\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/pesquisar/1x/B_compras.png);\n"
"    background-color: rgb(0, 53, 62);\n"
"    border:1px solid rgb(0, 53, 62);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 38, 44);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_Compras.setText("")
        self.pushButton_Compras.setObjectName("pushButton_Compras")
        self.gridLayout_2.addWidget(self.pushButton_Compras, 1, 6, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frameBody)
        self.frame_5.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 3, 1)
        self.pushButton_TI = QtWidgets.QPushButton(self.frameBody)
        self.pushButton_TI.setMinimumSize(QtCore.QSize(340, 340))
        self.pushButton_TI.setMaximumSize(QtCore.QSize(500, 500))
        self.pushButton_TI.setStyleSheet("QPushButton {\n"
"    \n"
"    background-image: url(:/pesquisar/1x/B_tecnologiahover.png);\n"
"    background-position:center;\n"
"    background-repeat: no-repeat;\n"
"    background-color: rgb(252, 252, 242);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/pesquisar/1x/B_tecnologia.png);\n"
"    background-color: rgb(0, 53, 62);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 38, 44);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_TI.setText("")
        self.pushButton_TI.setObjectName("pushButton_TI")
        self.gridLayout_2.addWidget(self.pushButton_TI, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.frameBody)
        self.frameRodape = QtWidgets.QFrame(self.centralwidget)
        self.frameRodape.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frameRodape.setStyleSheet("background-color: rgb(199, 211, 0);")
        self.frameRodape.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRodape.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRodape.setObjectName("frameRodape")
        self.verticalLayout.addWidget(self.frameRodape)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_usuario.setText(_translate("MainWindow", "USUÁRIO"))
        self.pushButton_perfil.setText(_translate("MainWindow", "PERFIL"))
        self.pushButton_sair.setText(_translate("MainWindow", "SAIR"))
        self.lineEdit_pesquisar.setPlaceholderText(_translate("MainWindow", "Pesquisar"))
        self.label.setText(_translate("MainWindow", "TECNOLOGIA"))
        self.label_2.setText(_translate("MainWindow", "RH"))
        self.label_3.setText(_translate("MainWindow", "COMPRAS"))
import IconPesquisar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
